command_timeout = 500

[character]

[username]

[directory]
fish_style_pwd_dir_length = 1
read_only = "  "
style = "#4169e1"
truncate_to_repo = true
truncation_length = 0
format = "[](bg:$style fg:black)[$path[$read_only]($read_only_style bg:$style)](bg:$style)[](fg:$style) "

[cmd_duration]
min_time = 50
show_milliseconds = true
show_notifications = true
min_time_to_notify = 20_000
format = "[ $duration]($style)"

[jobs]
symbol = " "

# harware config
[battery]
unknown_symbol = " "
empty_symbol = " "
discharging_symbol = " "
charging_symbol = " "
full_symbol = " "

  [[battery.display]]
  threshold = 10
  style = "bold fg:red"

  [[battery.display]]
  threshold = 30
  style = "fg:#ff8800"

  [[battery.display]]
  threshold = 50
  style = "fg:yellow"

[memory_usage]
disabled = true
symbol = " "

[time]
disabled = false
style = "#4169e1"
format = "[ $time ](fg:$style)"

[status]
disabled = false
style = "red"
symbol = "\\(╯°□°）╯︵ ┻━┻ "
format = "\b[](bg:$style fg:#4169e1)[$symbol$status](bg:$style)[](fg:$style)"

# VCS
[git_branch]
symbol = "  "
style = "#f05133"
format = "\b\b[](fg:#4169e1 bg:$style)[$symbol$branch](fg:white bg:$style)[](fg:$style) "

[git_commit]
style = "#f05133"
format = "\b\b[ ﰖ $hash](fg:white bg:$style)[](fg:$style) "

[git_state]
am = "APPLYING-MAILBOX"
am_or_rebase = "APPLYING-MAILBOX/REBASE"
style = "#f05133"
format = "\b\b[ \\($state( $progress_current/$progress_total)\\)](fg:white bg:$style)[](fg:$style) "

[git_status]
style = "#f05133"
format = "($all_status$ahead_behind\b )"
conflicted = "[ ](fg:88)[   ${count} ](fg:white bg:88)[ ](fg:88)"
staged = "[M$count ](fg:green)"
modified = "[M${count} ](fg:red)"
renamed = "[R${count} ](fg:208)"
deleted = "[ ${count} ](fg:208)"
untracked = "[?${count} ](fg:red)"
stashed = " ${count} "
ahead = "[ ${count} ](fg:purple)"
behind = "[ ${count} ](fg:yellow)"
diverged = "[](fg:88)[  נּ ](fg:white bg:88)[ ${ahead_count} ](fg:purple bg:88)[ ${behind_count} ](fg:yellow bg:88)[ ](fg:88)"

[shlvl]
disabled = false
style = "fg:bright-blue"
symbol = " "

[env_var]
# variable = "EDITOR"
# format = "editing with [$env_value]($style)"

# techno specific
[aws]
symbol = " "
format = 'on [$symbol$profile(\($region\))]($style) '
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[swift]
symbol = "ﯣ "

[rust]
symbol = " "
