function _create_shortcut_aliases {
  command=$1

  alias dbl="$command build"
  alias dcin="$command container inspect"
  alias dcls="$command container ls"
  alias dclsa="$command container ls -a"
  alias dib="$command image build"
  alias dii="$command image inspect"
  alias dils="$command image ls"
  alias dipu="$command image push"
  alias dirm="$command image rm"
  alias dit="$command image tag"
  alias dlo="$command container logs"
  alias dnc="$command network create"
  alias dncn="$command network connect"
  alias dndcn="$command network disconnect"
  alias dni="$command network inspect"
  alias dnls="$command network ls"
  alias dnrm="$command network rm"
  alias dpo="$command container port"
  alias dpu="$command pull"
  alias dr="$command container run"
  alias drit="$command container run -it"
  alias drm="$command container rm"
  alias 'drm!'="$command container rm -f"
  alias dst="$command container start"
  alias drs="$command container restart"
  alias dsta="$command stop $($command ps -q)"
  alias dstp="$command container stop"
  alias dtop="$command top"
  alias dvi="$command volume inspect"
  alias dvls="$command volume ls"
  alias dvprune="$command volume prune"
  alias dxc="$command container exec"
  alias dxcit="$command container exec -it"
}
